// Static mapping of all ISO country codes to their coordinates
export const countryCoordinates = {
  AD: { lat: 42.5, lng: 1.5, name: 'Andorra' },
  AE: { lat: 24, lng: 54, name: 'United Arab Emirates' },
  AF: { lat: 33, lng: 65, name: 'Afghanistan' },
  AG: { lat: 17.05, lng: -61.8, name: 'Antigua and Barbuda' },
  AI: { lat: 18.25, lng: -63.17, name: 'Anguilla' },
  AL: { lat: 41, lng: 20, name: 'Albania' },
  AM: { lat: 40, lng: 45, name: 'Armenia' },
  AO: { lat: -12.5, lng: 18.5, name: 'Angola' },
  AR: { lat: -34, lng: -64, name: 'Argentina' },
  AS: { lat: -14.33, lng: -170, name: 'American Samoa' },
  AT: { lat: 47.33, lng: 13.33, name: 'Austria' },
  AU: { lat: -27, lng: 133, name: 'Australia' },
  AW: { lat: 12.5, lng: -69.97, name: 'Aruba' },
  AZ: { lat: 40.5, lng: 47.5, name: 'Azerbaijan' },
  BA: { lat: 44, lng: 18, name: 'Bosnia and Herzegovina' },
  BB: { lat: 13.17, lng: -59.53, name: 'Barbados' },
  BD: { lat: 24, lng: 90, name: 'Bangladesh' },
  BE: { lat: 50.83, lng: 4, name: 'Belgium' },
  BF: { lat: 13, lng: -2, name: 'Burkina Faso' },
  BG: { lat: 43, lng: 25, name: 'Bulgaria' },
  BH: { lat: 26, lng: 50.55, name: 'Bahrain' },
  BI: { lat: -3.5, lng: 30, name: 'Burundi' },
  BJ: { lat: 9.5, lng: 2.25, name: 'Benin' },
  BM: { lat: 32.33, lng: -64.75, name: 'Bermuda' },
  BN: { lat: 4.5, lng: 114.67, name: 'Brunei' },
  BO: { lat: -17, lng: -65, name: 'Bolivia' },
  BR: { lat: -10, lng: -55, name: 'Brazil' },
  BS: { lat: 24.25, lng: -76, name: 'Bahamas' },
  BT: { lat: 27.5, lng: 90.5, name: 'Bhutan' },
  BW: { lat: -22, lng: 24, name: 'Botswana' },
  BY: { lat: 53, lng: 28, name: 'Belarus' },
  BZ: { lat: 17.25, lng: -88.75, name: 'Belize' },
  CA: { lat: 60, lng: -95, name: 'Canada' },
  CD: { lat: 0, lng: 25, name: 'Democratic Republic of the Congo' },
  CF: { lat: 7, lng: 21, name: 'Central African Republic' },
  CG: { lat: -1, lng: 15, name: 'Republic of the Congo' },
  CH: { lat: 47, lng: 8, name: 'Switzerland' },
  CI: { lat: 8, lng: -5, name: 'Ivory Coast' },
  CL: { lat: -30, lng: -71, name: 'Chile' },
  CM: { lat: 6, lng: 12, name: 'Cameroon' },
  CN: { lat: 35, lng: 105, name: 'China' },
  CO: { lat: 4, lng: -72, name: 'Colombia' },
  CR: { lat: 10, lng: -84, name: 'Costa Rica' },
  CU: { lat: 21.5, lng: -80, name: 'Cuba' },
  CV: { lat: 16, lng: -24, name: 'Cape Verde' },
  CY: { lat: 35, lng: 33, name: 'Cyprus' },
  CZ: { lat: 49.75, lng: 15.5, name: 'Czech Republic' },
  DE: { lat: 51, lng: 9, name: 'Germany' },
  DJ: { lat: 11.5, lng: 43, name: 'Djibouti' },
  DK: { lat: 56, lng: 10, name: 'Denmark' },
  DM: { lat: 15.42, lng: -61.33, name: 'Dominica' },
  DO: { lat: 19, lng: -70.67, name: 'Dominican Republic' },
  DZ: { lat: 36, lng: 3, name: 'Algeria' },
  EC: { lat: -2, lng: -77.5, name: 'Ecuador' },
  EE: { lat: 59, lng: 26, name: 'Estonia' },
  EG: { lat: 27, lng: 30, name: 'Egypt' },
  EH: { lat: 24.5, lng: -13, name: 'Western Sahara' },
  ER: { lat: 15, lng: 39, name: 'Eritrea' },
  ES: { lat: 40, lng: -4, name: 'Spain' },
  ET: { lat: 8, lng: 38, name: 'Ethiopia' },
  FI: { lat: 64, lng: 26, name: 'Finland' },
  FJ: { lat: -18, lng: 175, name: 'Fiji' },
  FK: { lat: -51.75, lng: -59, name: 'Falkland Islands' },
  FM: { lat: 6.92, lng: 158.25, name: 'Micronesia' },
  FO: { lat: 62, lng: -7, name: 'Faroe Islands' },
  FR: { lat: 46, lng: 2, name: 'France' },
  GA: { lat: -1, lng: 11.75, name: 'Gabon' },
  GB: { lat: 54, lng: -2, name: 'United Kingdom' },
  GD: { lat: 12.12, lng: -61.67, name: 'Grenada' },
  GE: { lat: 42, lng: 43.5, name: 'Georgia' },
  GF: { lat: 4, lng: -53, name: 'French Guiana' },
  GH: { lat: 8, lng: -2, name: 'Ghana' },
  GI: { lat: 36.18, lng: -5.37, name: 'Gibraltar' },
  GL: { lat: 72, lng: -40, name: 'Greenland' },
  GM: { lat: 13.47, lng: -16.57, name: 'Gambia' },
  GN: { lat: 11, lng: -10, name: 'Guinea' },
  GP: { lat: 16.25, lng: -61.58, name: 'Guadeloupe' },
  GQ: { lat: 2, lng: 10, name: 'Equatorial Guinea' },
  GR: { lat: 39, lng: 22, name: 'Greece' },
  GT: { lat: 15.5, lng: -90.25, name: 'Guatemala' },
  GU: { lat: 13.47, lng: 144.78, name: 'Guam' },
  GW: { lat: 12, lng: -15, name: 'Guinea-Bissau' },
  GY: { lat: 5, lng: -59, name: 'Guyana' },
  HK: { lat: 22.25, lng: 114.17, name: 'Hong Kong' },
  HN: { lat: 15, lng: -86.5, name: 'Honduras' },
  HR: { lat: 45.17, lng: 15.5, name: 'Croatia' },
  HT: { lat: 19, lng: -72.42, name: 'Haiti' },
  HU: { lat: 47, lng: 20, name: 'Hungary' },
  ID: { lat: -5, lng: 120, name: 'Indonesia' },
  IE: { lat: 53, lng: -8, name: 'Ireland' },
  IL: { lat: 31.5, lng: 34.75, name: 'Israel' },
  IN: { lat: 20, lng: 77, name: 'India' },
  IQ: { lat: 33, lng: 44, name: 'Iraq' },
  IR: { lat: 32, lng: 53, name: 'Iran' },
  IS: { lat: 65, lng: -18, name: 'Iceland' },
  IT: { lat: 42.83, lng: 12.83, name: 'Italy' },
  JM: { lat: 18.25, lng: -77.5, name: 'Jamaica' },
  JO: { lat: 31, lng: 36, name: 'Jordan' },
  JP: { lat: 36, lng: 138, name: 'Japan' },
  KE: { lat: 1, lng: 38, name: 'Kenya' },
  KG: { lat: 41, lng: 75, name: 'Kyrgyzstan' },
  KH: { lat: 13, lng: 105, name: 'Cambodia' },
  KI: { lat: 1.42, lng: 173, name: 'Kiribati' },
  KM: { lat: -12.17, lng: 44.25, name: 'Comoros' },
  KP: { lat: 40, lng: 127, name: 'North Korea' },
  KR: { lat: 37, lng: 127.5, name: 'South Korea' },
  KW: { lat: 29.34, lng: 47.66, name: 'Kuwait' },
  KY: { lat: 19.5, lng: -80.5, name: 'Cayman Islands' },
  KZ: { lat: 48, lng: 68, name: 'Kazakhstan' },
  LA: { lat: 18, lng: 105, name: 'Laos' },
  LB: { lat: 33.83, lng: 35.83, name: 'Lebanon' },
  LC: { lat: 13.88, lng: -61.13, name: 'Saint Lucia' },
  LI: { lat: 47.17, lng: 9.53, name: 'Liechtenstein' },
  LK: { lat: 7, lng: 81, name: 'Sri Lanka' },
  LR: { lat: 6.5, lng: -9.5, name: 'Liberia' },
  LS: { lat: -29.5, lng: 28.5, name: 'Lesotho' },
  LT: { lat: 56, lng: 24, name: 'Lithuania' },
  LU: { lat: 49.75, lng: 6.17, name: 'Luxembourg' },
  LV: { lat: 57, lng: 25, name: 'Latvia' },
  LY: { lat: 25, lng: 17, name: 'Libya' },
  MA: { lat: 32, lng: -5, name: 'Morocco' },
  MC: { lat: 43.73, lng: 7.4, name: 'Monaco' },
  MD: { lat: 47, lng: 29, name: 'Moldova' },
  ME: { lat: 42, lng: 19, name: 'Montenegro' },
  MG: { lat: -20, lng: 47, name: 'Madagascar' },
  MH: { lat: 9, lng: 168, name: 'Marshall Islands' },
  MK: { lat: 41.83, lng: 22, name: 'North Macedonia' },
  ML: { lat: 17, lng: -4, name: 'Mali' },
  MM: { lat: 22, lng: 98, name: 'Myanmar' },
  MN: { lat: 46, lng: 105, name: 'Mongolia' },
  MO: { lat: 22.17, lng: 113.55, name: 'Macau' },
  MP: { lat: 15.2, lng: 145.75, name: 'Northern Mariana Islands' },
  MQ: { lat: 14.67, lng: -61, name: 'Martinique' },
  MR: { lat: 20, lng: -12, name: 'Mauritania' },
  MS: { lat: 16.75, lng: -62.2, name: 'Montserrat' },
  MT: { lat: 35.83, lng: 14.58, name: 'Malta' },
  MU: { lat: -20.28, lng: 57.55, name: 'Mauritius' },
  MV: { lat: 3.25, lng: 73, name: 'Maldives' },
  MW: { lat: -13.5, lng: 34, name: 'Malawi' },
  MX: { lat: 23, lng: -102, name: 'Mexico' },
  MY: { lat: 2.5, lng: 112.5, name: 'Malaysia' },
  MZ: { lat: -18.25, lng: 35, name: 'Mozambique' },
  NA: { lat: -22, lng: 17, name: 'Namibia' },
  NC: { lat: -21.5, lng: 165.5, name: 'New Caledonia' },
  NE: { lat: 16, lng: 8, name: 'Niger' },
  NF: { lat: -29.03, lng: 167.95, name: 'Norfolk Island' },
  NG: { lat: 10, lng: 8, name: 'Nigeria' },
  NI: { lat: 13, lng: -85, name: 'Nicaragua' },
  NL: { lat: 52.5, lng: 5.75, name: 'Netherlands' },
  NO: { lat: 62, lng: 10, name: 'Norway' },
  NP: { lat: 28, lng: 84, name: 'Nepal' },
  NR: { lat: -0.53, lng: 166.92, name: 'Nauru' },
  NU: { lat: -19.03, lng: -169.87, name: 'Niue' },
  NZ: { lat: -41, lng: 174, name: 'New Zealand' },
  OM: { lat: 21, lng: 57, name: 'Oman' },
  PA: { lat: 9, lng: -80, name: 'Panama' },
  PE: { lat: -10, lng: -76, name: 'Peru' },
  PF: { lat: -15, lng: -140, name: 'French Polynesia' },
  PG: { lat: -6, lng: 147, name: 'Papua New Guinea' },
  PH: { lat: 13, lng: 122, name: 'Philippines' },
  PK: { lat: 30, lng: 70, name: 'Pakistan' },
  PL: { lat: 52, lng: 20, name: 'Poland' },
  PM: { lat: 46.83, lng: -56.33, name: 'Saint Pierre and Miquelon' },
  PR: { lat: 18.25, lng: -66.5, name: 'Puerto Rico' },
  PS: { lat: 32, lng: 35.25, name: 'Palestine' },
  PT: { lat: 39.5, lng: -8, name: 'Portugal' },
  PW: { lat: 7.5, lng: 134.5, name: 'Palau' },
  PY: { lat: -23, lng: -58, name: 'Paraguay' },
  QA: { lat: 25.5, lng: 51.25, name: 'Qatar' },
  RE: { lat: -21.1, lng: 55.6, name: 'Reunion' },
  RO: { lat: 46, lng: 25, name: 'Romania' },
  RS: { lat: 44, lng: 21, name: 'Serbia' },
  RU: { lat: 60, lng: 100, name: 'Russia' },
  RW: { lat: -2, lng: 30, name: 'Rwanda' },
  SA: { lat: 25, lng: 45, name: 'Saudi Arabia' },
  SB: { lat: -8, lng: 159, name: 'Solomon Islands' },
  SC: { lat: -4.58, lng: 55.67, name: 'Seychelles' },
  SD: { lat: 15, lng: 30, name: 'Sudan' },
  SE: { lat: 62, lng: 15, name: 'Sweden' },
  SG: { lat: 1.37, lng: 103.8, name: 'Singapore' },
  SI: { lat: 46, lng: 15, name: 'Slovenia' },
  SK: { lat: 48.67, lng: 19.5, name: 'Slovakia' },
  SL: { lat: 8.5, lng: -11.5, name: 'Sierra Leone' },
  SM: { lat: 43.77, lng: 12.42, name: 'San Marino' },
  SN: { lat: 14.73, lng: -17.63, name: 'Senegal' },
  SO: { lat: 10, lng: 49, name: 'Somalia' },
  SR: { lat: 4, lng: -56, name: 'Suriname' },
  SS: { lat: 7.91, lng: 31.04, name: 'South Sudan' },
  ST: { lat: 1, lng: 7, name: 'Sao Tome and Principe' },
  SV: { lat: 13.75, lng: -88.89, name: 'El Salvador' },
  SX: { lat: 18.07, lng: -63.05, name: 'Sint Maarten' },
  SY: { lat: 35, lng: 38, name: 'Syria' },
  SZ: { lat: -26.5, lng: 31.5, name: 'Eswatini' },
  TD: { lat: 15, lng: 19, name: 'Chad' },
  TG: { lat: 8, lng: 1.13, name: 'Togo' },
  TH: { lat: 15, lng: 100, name: 'Thailand' },
  TJ: { lat: 39, lng: 71, name: 'Tajikistan' },
  TL: { lat: -8.27, lng: 125.67, name: 'Timor-Leste' },
  TM: { lat: 40, lng: 60, name: 'Turkmenistan' },
  TN: { lat: 34, lng: 9, name: 'Tunisia' },
  TO: { lat: -21.13, lng: -175.2, name: 'Tonga' },
  TR: { lat: 39, lng: 35, name: 'Turkey' },
  TT: { lat: 11, lng: -61, name: 'Trinidad and Tobago' },
  TV: { lat: -8, lng: 178, name: 'Tuvalu' },
  TW: { lat: 23.5, lng: 121, name: 'Taiwan' },
  TZ: { lat: -6, lng: 35, name: 'Tanzania' },
  UA: { lat: 49, lng: 32, name: 'Ukraine' },
  UG: { lat: 1, lng: 32, name: 'Uganda' },
  US: { lat: 37.0902, lng: -95.7129, name: 'United States' },
  UY: { lat: -33, lng: -56, name: 'Uruguay' },
  UZ: { lat: 41, lng: 64, name: 'Uzbekistan' },
  VA: { lat: 41.9, lng: 12.45, name: 'Vatican City' },
  VC: { lat: 13.25, lng: -61.2, name: 'Saint Vincent and the Grenadines' },
  VE: { lat: 8, lng: -66, name: 'Venezuela' },
  VG: { lat: 18.42, lng: -64.62, name: 'British Virgin Islands' },
  VI: { lat: 18.33, lng: -64.83, name: 'U.S. Virgin Islands' },
  VN: { lat: 16, lng: 108, name: 'Vietnam' },
  VU: { lat: -16, lng: 167, name: 'Vanuatu' },
  WF: { lat: -13.3, lng: -176.2, name: 'Wallis and Futuna' },
  WS: { lat: -13.76, lng: -172.15, name: 'Samoa' },
  YE: { lat: 15, lng: 48, name: 'Yemen' },
  YT: { lat: -12.83, lng: 45.17, name: 'Mayotte' },
  ZA: { lat: -30.55, lng: 22.94, name: 'South Africa' },
  ZM: { lat: -10.76, lng: 28.76, name: 'Zambia' },
  ZW: { lat: -19.02, lng: 29.15, name: 'Zimbabwe' }
};

export function getCountryLocation(countryCode) {
  const country = countryCoordinates[countryCode.toUpperCase()];
  if (!country) {
    console.warn(`No coordinates found for country code: ${countryCode}`);
    return null;
  }
  return {
    latitude: country.lat,
    longitude: country.lng,
    country: country.name,
    city: country.name // Using country name as city for Spotify market data
  };
}

// Add this function to check for missing countries
export function validateCountryCode(code) {
  if (!countryCoordinates[code.toUpperCase()]) {
    console.warn(`Missing coordinates for country code: ${code}`);
    return false;
  }
  return true;
} 